/**
 * Free Image Generation Service — Module 7
 *
 * Strategy (all free, no API key needed):
 *  Primary:  Pollinations.ai — free, no key, no rate limit (fair use)
 *  Fallback: Picsum Photos placeholder (always works, great for dev)
 *
 * Pollinations.ai is a free, open-source AI image generation service
 * that uses Stable Diffusion under the hood.
 * Docs: https://pollinations.ai
 *
 * For production with better quality, self-host:
 *  - Automatic1111 (Stable Diffusion WebUI) — set STABLE_DIFFUSION_URL in .env
 *  - ComfyUI
 */

import { uploadImageFromUrl } from "../utils/db/cloudinary.js";

/**
 * Generate a blog thumbnail image.
 * Uses Google Gemini (Imagen 3) API as primary, with Pollinations.ai (free) as fallback.
 *
 * @param {string} prompt - Image generation prompt
 * @returns {Promise<{ imageUrl: string, cloudinaryUrl: string|null, publicId: string|null }>}
 */
export const generateBlogThumbnail = async (prompt) => {
  let imageUrl;
  const apiKey = process.env.GEMINI_API_KEY;

  try {
    if (!apiKey) {
      console.warn("GEMINI_API_KEY not found, falling back to Pollinations.ai");
      imageUrl = generatePollinationsUrl(prompt);
    } else {
      // Use Gemini Imagen 3
      imageUrl = await generateWithGemini(prompt, apiKey);
    }

    // Upload to Cloudinary for permanent CDN storage
    const { cloudinaryUrl, publicId } = await uploadImageFromUrl(
      imageUrl,
      "scriptify-ai/thumbnails"
    );
    
    return { imageUrl, cloudinaryUrl, publicId };
  } catch (err) {
    console.error("Primary generation or upload failed:", err.message);
    
    // If Gemini failed, try Pollinations.ai as a fallback before completely giving up
    if (apiKey) {
      console.log("Attempting fallback to Pollinations.ai...");
      try {
        imageUrl = generatePollinationsUrl(prompt);
        const { cloudinaryUrl, publicId } = await uploadImageFromUrl(
          imageUrl,
          "scriptify-ai/thumbnails"
        );
        return { imageUrl, cloudinaryUrl, publicId };
      } catch (fallbackErr) {
        console.error("Fallback upload also failed:", fallbackErr.message);
      }
    }
    
    return { imageUrl: imageUrl || null, cloudinaryUrl: null, publicId: null };
  }
};

/**
 * Generate image with Google Gemini (Imagen 3)
 * @param {string} prompt 
 * @param {string} apiKey 
 * @returns {Promise<string>} data URL
 */
const generateWithGemini = async (prompt, apiKey) => {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${apiKey}`;
  
  const cleanPrompt = `${prompt}, professional blog cover image, high quality, editorial photography style, visually stunning, 4k, sharp, no text, no watermark`;

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      instances: [{ prompt: cleanPrompt }],
      parameters: {
        sampleCount: 1,
        aspectRatio: "16:9" // Ideal for blog covers
      }
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini Imagen API error ${response.status}: ${errText}`);
  }

  const data = await response.json();
  
  if (data.predictions && data.predictions.length > 0) {
    const base64Image = data.predictions[0].bytesBase64;
    const mimeType = data.predictions[0].mimeType || "image/jpeg";
    return `data:${mimeType};base64,${base64Image}`;
  } else {
    throw new Error("No image generated by Gemini");
  }
};

/**
 * Pollinations.ai — completely free, no key, returns a direct image URL.
 * Encodes the prompt into a URL that serves a generated image.
 *
 * @param {string} prompt
 * @returns {string} image URL
 */
const generatePollinationsUrl = (prompt) => {
  const cleanPrompt = prompt
    .replace(/[^a-zA-Z0-9 .,!?'-]/g, " ")
    .trim()
    .substring(0, 500);

  const encoded = encodeURIComponent(
    `${cleanPrompt}, professional blog cover image, high quality, editorial style, no text, no watermark, clean background, 4k, sharp`
  );

  const width = 1200;
  const height = 630;
  const seed = Math.floor(Math.random() * 1000000);

  return `https://image.pollinations.ai/prompt/${encoded}?width=${width}&height=${height}&seed=${seed}&nologo=true`;
};